version: "3"

services:
  db:
    image: mongo:4.4.4
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ../data/dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
